import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AppHeader from "../components/header/app.header";
import NextAuthWrapper from "../lib/next.auth.wrapper";
// import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ margin: "0" }}>
        {/* share session giữa các layout */}
        <NextAuthWrapper>
          <AppHeader />
          {children}
          <div style={{ marginBottom: "100px" }}></div>
        </NextAuthWrapper>
      </body>
    </html>
  );
}
